# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11f68cc10d86a5b739e3c1c34be8cd15ff68efb6a8abf14d000af3b9d894791a626b5e379e6e054d9eb626981093ab4e1fa0ef24b8bca40aea4b55c93736243d

test:
  secret_key_base: 8c12468fc4dd2a58299ddc56530a7b9c9bf215189afccf8cfc5e64755d302f39144f64572dc19e9119dd7e016605cf32940c31a901555149324a4f64b5ffda91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
